### ISSUE TITLE
(1) Install Dunning on Production and Staging

### ISSUE THREAD

**Issue by dottenbr** [newmatik/dunning#1]

**Comment by creamdory** [comment]
@dottenbr I noticed that this app is not yet in V12 format. Also I got an error when installing the app in my local which is in V12.

<img width="1361" alt="doridelcahanap@dori: ~:Development:dev_py2:frappe-bench 2019-11-26 10-14-21" src="https://user-images.githubusercontent.com/21003054/69593946-c99c5b80-1035-11ea-872a-753bed076d0b.png">

Should I fix in our fork?

**Comment by dottenbr** [comment]
I think you should fix it and create PR

**Comment by KanchanChauhan** [comment]
@creamdory @dottenbr Dunning installed on STAGING
<img width="931" alt="Screen Shot 2019-11-28 at 6 11 04 PM" src="https://user-images.githubusercontent.com/16913064/69807110-7a5b5400-120a-11ea-834f-75bc2fdc6e72.png">

**Comment by dottenbr** [comment]
@KanchanChauhan did this require any fixes? If so can you PR against our Repo and then against the repo we forked from?

**Comment by KanchanChauhan** [comment]
@dottenbr @creamdory We don't have to PR anything, we need to manually delete 2 doctypes related to GCalendar. While troubleshooting I realized there is a patch in SOURCES.txt inside frappe.egg-info which does not run on migrate and is weird. Anyhow, we can manually delete them and it is fine after that.

**Comment by creamdory** [comment]
### STAGING TEST PASS

![dunning](https://user-images.githubusercontent.com/21003054/69841576-c2c25280-129a-11ea-899c-316b3007a445.gif)

**Comment by creamdory** [comment]
Keeping it open until V12. Assigning myself too since I will be installing together with https://github.com/newmatik/newmatik/issues/2315

**Comment by creamdory** [comment]
### INSTALLED IN PROD

![dunning](https://user-images.githubusercontent.com/21003054/69897249-26747a80-1384-11ea-926a-53fc191c9790.gif)
