### ISSUE TITLE
(1) Remove Quick Add

### ISSUE THREAD

**Issue by dottenbr** [newmatik/dunning#11]
I don't think there is any use-case I can imagine where you want to quick-add dunning so please remove it.

![image](https://user-images.githubusercontent.com/9136094/70244018-f6f2b300-1773-11ea-8ffb-dbd47b1450db.png)

**Comment by creamdory** [comment]
### STAGING TEST PASS

![dunning](https://user-images.githubusercontent.com/21003054/70290025-92863100-1811-11ea-87ab-1440aeb8f56e.gif)
