### ISSUE TITLE
(1) Dunning not Selecting Proper Print Format

### ISSUE THREAD

**Issue by dottenbr** [newmatik/dunning#13]
![image](https://user-images.githubusercontent.com/9136094/70244317-7a140900-1774-11ea-92de-ccbe36ed24c1.png)

**Comment by creamdory** [comment]
### STAGING TEST PASS

![print](https://user-images.githubusercontent.com/21003054/70290069-b5b0e080-1811-11ea-8340-22088f5ea19e.gif)
