### ISSUE TITLE
(1) Dunning Print Format Changes

### ISSUE THREAD

**Issue by dottenbr** [newmatik/dunning#14]
- [x] Fix document title to just have title and document name in second line (similar to sales invoice)

![image](https://user-images.githubusercontent.com/9136094/70244613-01617c80-1775-11ea-92a6-bb130f07fde0.png)

- [x] Remove "Shipping Address", "Billing Address" and "Customer Contact Details"

- [x] Add how many days overdue

- [x] Add "Text section" from Dunning Type before table (see separate issue https://github.com/newmatik/dunning/issues/15)

![image](https://user-images.githubusercontent.com/9136094/70244738-4a193580-1775-11ea-9939-59fd6867965c.png)

![image](https://user-images.githubusercontent.com/9136094/70244557-e8f16200-1774-11ea-97f8-27046643db69.png)

**Comment by dottenbr** [comment]
![image](https://user-images.githubusercontent.com/9136094/70308577-e1c96300-180b-11ea-9cd7-107543e47cf9.png)

Use same style as delivery note, sales invoice, quotation ... etc

**Comment by creamdory** [comment]
### STAGING TEST PASS

<img width="1269" alt="PR-DE-19-00003 2019-12-06 17-31-52" src="https://user-images.githubusercontent.com/21003054/70312302-532a0580-184e-11ea-90b2-ac0ab64d424a.png">
