### ISSUE TITLE
(1) Dunning Type Text Block

### ISSUE THREAD

**Issue by dottenbr** [newmatik/dunning#15]
Every dunning type has a unique text block that must also be translatable into multiple languages. A first dunning document might be a friendly payment reminder, while the last payment reminder might threaten leagal action. In order to do this programatically I want to add a "Dunning Type Text Block" as a DocType which will be a Child Table in "Dunning Type". These can be written and saved for all languages.

![image](https://user-images.githubusercontent.com/9136094/70245462-6073c100-1776-11ea-853e-7925b24fc698.png)

Within the print format, the proper text block must be displayed in the correct language. If no text block exists, keep empty.

**Comment by dottenbr** [comment]
@KanchanChauhan changes made live by me on the staging server, you can copy or push.

**Comment by dottenbr** [comment]
@KanchanChauhan if possible please enable that text block to parse stuff like {{document.due_date}} correctly so we can generate stuff like:

```
This is a reminder that you have not paid invoice {{invoice}} with the amount of {{amount}}which was due on {{duedate}}.

This is a reminder that you have not paid invoice INV-0001 with the amount of 500 USD which was due on 01/01/2019.
```

**Comment by KanchanChauhan** [comment]
@dottenbr I cannot see you changes on staging. But I have created the doctype in a my local. Few things need to clarify.
1. Why do we need Langauge, it can be a translatable text and we just need to add translations. But if we still need it, there is no way to know before rendering what language we are printing in. So we need a new field Language on Dunning and based on that we will pull the Text Block. Let me know if I should proceed with it.
2. Parsing stuff is doable but I need some time for this, will have to do something like Terms and Conditions.

**Comment by dottenbr** [comment]
@KanchanChauhan the issue is that different languages might have very different grammatical structures. If we just add language that seems like it is an elegant solution

**Comment by KanchanChauhan** [comment]
@dottenbr got it, I will add language selector to print setting, that is how we will know which language text to get.

**Comment by dottenbr** [comment]
There is always a language selector in print setting already. I don’t know what you mean. You will just handle that in the code of the print format with conditionals.

**Comment by KanchanChauhan** [comment]
@dottenbr On the print there is language but we need it before. Since we are allowing jinja template and field parsing, we pull text block to Dunning, not on print directly. So we will need the language field on Dunning to pull correct language Text Block.

**Comment by dottenbr** [comment]
Then I suppose we need a different solution

**Comment by dottenbr** [comment]
@KanchanChauhan got it, I think this is a viable solution then. Not sure how others see that or if there is a precedent in ERPNext to handle it like this but I think this makes sense.

**Comment by creamdory** [comment]
### In Prod
