### ISSUE TITLE
(1) Invoices Selection not filtered to Overdue

### ISSUE THREAD

**Issue by dottenbr** [newmatik/dunning#23]
Currently, all **open** invoices are shown, however it should only show **overdue** invoices.

![image](https://user-images.githubusercontent.com/9136094/70422885-c3ae6d80-1a6c-11ea-87b9-17d7057bb580.png)

**Comment by creamdory** [comment]
### PROD TEST PASS

<img width="926" alt="Neu Mahnung 1 - Neu Mahnung 1 2019-12-10 15-17-44" src="https://user-images.githubusercontent.com/21003054/70505406-ea4ed000-1b62-11ea-8c4b-c66218f83e55.png">
