### ISSUE TITLE
(1) Dunning Print fixes

### ISSUE THREAD

**Issue by KanchanChauhan** [newmatik/dunning#24]
<img width="595" alt="70424385-56630280-1a95-11ea-8ba4-b3a9c6c675c9 png (2784×2898) 2020-06-02 17-21-58" src="https://user-images.githubusercontent.com/21003054/83503483-b642df00-a4f5-11ea-9829-218507195145.png">

<img width="926" alt="70424394-5a8f2000-1a95-11ea-95b4-8cd2f68fec5c png (1056×356) 2020-06-02 17-23-59" src="https://user-images.githubusercontent.com/21003054/83503655-fe620180-a4f5-11ea-8d26-185e702e1768.png">

![image](https://user-images.githubusercontent.com/16913064/70424410-5e22a700-1a95-11ea-91f9-718eb2c57512.png)

![image](https://user-images.githubusercontent.com/16913064/70424413-61b62e00-1a95-11ea-9ac2-bd268304a8e6.png)

![image](https://user-images.githubusercontent.com/16913064/70424425-6549b500-1a95-11ea-9b7d-9aecba8579e3.png)

**Comment by creamdory** [comment]
### PROD TEST PASS

<img width="688" alt="PR-DE-19-00011 - PR-DE-19-00011 2019-12-10 15-41-12" src="https://user-images.githubusercontent.com/21003054/70505691-9395c600-1b63-11ea-959d-8c36b0bc12c0.png">

<img width="604" alt="PR-DE-19-00011 - PR-DE-19-00011 2019-12-10 15-41-57" src="https://user-images.githubusercontent.com/21003054/70505714-a27c7880-1b63-11ea-8633-81b49235295d.png">

<img width="227" alt="PR-DE-19-00011 - PR-DE-19-00011 2019-12-10 15-42-24" src="https://user-images.githubusercontent.com/21003054/70505740-b4f6b200-1b63-11ea-8aa4-cd3739764845.png">

<img width="395" alt="PR-DE-19-00011 - PR-DE-19-00011 2019-12-10 15-42-52" src="https://user-images.githubusercontent.com/21003054/70505763-c5a72800-1b63-11ea-8fff-0089671b8fdc.png">

<img width="224" alt="PR-DE-19-00008 - PR-DE-19-00008 2019-12-10 15-43-44" src="https://user-images.githubusercontent.com/21003054/70505857-ff782e80-1b63-11ea-840a-5f8c1eeddc87.png">
