### ISSUE TITLE
(1) Dunning Status Not Showing in List View

### ISSUE THREAD

**Issue by dottenbr** [newmatik/dunning#27]
It is showing as "Unclarified" even though it is clarified.

![image](https://user-images.githubusercontent.com/9136094/70432285-31639500-1a7f-11ea-89bd-4fe64127e919.png)

![image](https://user-images.githubusercontent.com/9136094/70432301-39233980-1a7f-11ea-9850-1df50338ff95.png)

**Comment by creamdory** [comment]
### PROD TEST PASS

<img width="1287" alt="Mahnung 2019-12-10 15-15-38" src="https://user-images.githubusercontent.com/21003054/70504115-0309b680-1b60-11ea-96fc-7cb52cebc7eb.png">

<img width="1186" alt="PR-DE-19-00011 - PR-DE-19-00011 2019-12-10 15-15-58" src="https://user-images.githubusercontent.com/21003054/70504153-174db380-1b60-11ea-8ba4-069b3e208e5c.png">
