### ISSUE TITLE
(1) Small Print Format Fix

### ISSUE THREAD

**Issue by dottenbr** [newmatik/dunning#29]
![image](https://user-images.githubusercontent.com/9136094/70524582-c8932000-1b45-11ea-8661-014766978f1e.png)

**Comment by creamdory** [comment]
### PROD TEST PASS

<img width="823" alt="Lütze Transportation GmbH - PR-DE-19-00011 2019-12-12 11-56-04" src="https://user-images.githubusercontent.com/21003054/70681462-6fa6c180-1cd6-11ea-998f-9fa5c90476cb.png">
