### ISSUE TITLE
(1) Print Format in PDF Chopping Off Text

### ISSUE THREAD

**Issue by dottenbr** [newmatik/dunning#30]
PDF print chops off text

![image](https://user-images.githubusercontent.com/9136094/70524853-5f5fdc80-1b46-11ea-844f-1136c61c46ef.png)

**Comment by creamdory** [comment]
### PROD TEST PASS

<img width="823" alt="Lütze Transportation GmbH - PR-DE-19-00011 2019-12-12 11-56-04" src="https://user-images.githubusercontent.com/21003054/70681482-83522800-1cd6-11ea-919c-411cf04cac29.png">

**Comment by dottenbr** [comment]
@creamdory did you test the PDF? The print preview always worked.

**Comment by creamdory** [comment]
@KanchanChauhan still chopping. The issue was with PDF view.

<img width="419" alt="frappe utils print_format download_pdf 2019-12-12 15-26-07" src="https://user-images.githubusercontent.com/21003054/70691407-fe760700-1cf3-11ea-875a-f39ec2affb1e.png">

**Comment by KanchanChauhan** [comment]
@creamdory Did some style changes to text in Dunning Type. It is fine now for all 3 types. None of the text is getting cut off.

Last Notice
<img width="1120" alt="Screen Shot 2019-12-12 at 1 54 35 PM" src="https://user-images.githubusercontent.com/16913064/70695129-0f6c4b80-1ce7-11ea-95d6-cd02b969b1d7.png">

Second Notice
<img width="1153" alt="Screen Shot 2019-12-12 at 1 54 05 PM" src="https://user-images.githubusercontent.com/16913064/70695131-0f6c4b80-1ce7-11ea-8052-c7617b4f408c.png">

Payment Reminder
<img width="1049" alt="Screen Shot 2019-12-12 at 1 53 23 PM" src="https://user-images.githubusercontent.com/16913064/70695133-1004e200-1ce7-11ea-82f0-78b41707470f.png">

**Comment by creamdory** [comment]
### PROD TEST PASS

Test with @KanchanChauhan .

<img width="1089" alt="frappe utils print_format download_pdf 2019-12-12 16-44-14" src="https://user-images.githubusercontent.com/21003054/70696470-bad4ca80-1cfe-11ea-905f-c75f2e5c50ce.png">
