### ISSUE TITLE
(1) Add Standard Filters

### ISSUE THREAD

**Issue by dottenbr** [newmatik/dunning#38]
![image](https://user-images.githubusercontent.com/9136094/72907594-6167ae80-3d34-11ea-8a7b-e0476caa5e65.png)

**Comment by creamdory** [comment]
### STAGING TEST PASS

Position not the same as mockup due to field index.

<img width="1218" alt="72948603-a1747300-3dc0-11ea-9cfa-b7ecfe21a3e9 gif (1424×718) 2020-06-02 17-18-47" src="https://user-images.githubusercontent.com/21003054/83503217-53514800-a4f5-11ea-9b65-56c0b0d2f4b3.png">
