### ISSUE TITLE
(1) [Dunning] Make Naming Series configurable

### ISSUE THREAD

**Issue by carstenblt** [newmatik/dunning#42]
The series is still hard coded `dunning/doctype/dunning/dunning.js`.

**Comment by dottenbr** [comment]
https://github.com/newmatik/dunning/issues/43

**Comment by KanchanChauhan** [comment]
It is now setup as other doctypes, there is a default naming series and user can add new series from Naming Series doctype.
<img width="697" alt="Screen Shot 2020-07-16 at 9 17 02 AM" src="https://user-images.githubusercontent.com/16913064/87624340-270c2680-c745-11ea-9eb6-34be28d3776f.png">
