### ISSUE TITLE
(1) [Dunning] Patch to create boilerplate texts

### ISSUE THREAD

**Issue by dottenbr** [newmatik/dunning#47]
Patch to create boilerplate texts for existing instances and new setups

**Comment by jeremythegreat01** [comment]
Un-assigning from Kanchan because she is offboarding.

Adding this to the backlog project.

**Comment by jeremythegreat01** [comment]
Closing this to clean up the queue and because the issue is from 2020.

If users still need the feature, a new issue should be created with better information.
