### ISSUE TITLE
(1) Change Number Series

### ISSUE THREAD

**Issue by dottenbr** [newmatik/dunning#7]
### Ratings:

Effort: **Low**
Complexity: **Low**
Unknown: **Low**

### Task

Currently, it is "MHG" which stands for **M**a**h**nun**g**. Internationally I suggest "PR" instead.

- [ ] For the app / core make it PR-000001
- [ ] For ESO make it PR-[company]-[year]-12345 e.g. PR-DE-19-00120

**Comment by KanchanChauhan** [comment]
@dottenbr For our custom naming, do we create custom script or make changes to our fork directly?

**Comment by dottenbr** [comment]
### STAGING TEST PASSED
